<?php

namespace coffre\appBundle\Entity;

use Symfony\Component\HttpFoundation\Session\Session;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository {

    public function All() {
        $qb = $this->createQueryBuilder('a');
        $session = new Session();

        $qb->select('a')->where('a.session = :session and a.clecontrole != 6')
                ->setParameter('session', $session->get('Session'));
              

        return $qb
                        ->getQuery()
                        ->getSingleResult()
        ;
    }

    public function CalculAll() {
        $session = new Session();

        $qb = $this->createQueryBuilder('a');

        $qb->select('sum(a.valeur)')->where('a.operateur = :op and a.session = :session and a.type != 6')->setParameter('op', $session->get('Codecaisse'))
                ->setParameter('session', $session->get('Session'));

        return $qb
                        ->getQuery()
                        ->getSingleResult()
        ;
    }

    public function CalculTitreAll() {
        $session = new Session();
        $qb = $this->createQueryBuilder('a');

        $qb->select('sum(a.valeur)')->where('a.session = :session and a.type != 6')
                ->setParameter('session', $session->get('Session'));


        return $qb
                        ->getQuery()
                        ->getSingleResult()
        ;
    }

    public function CalculNbreAll() {
        $session = new Session();
        $qb = $this->createQueryBuilder('a');

        $qb->select('count(a.valeur)')->where('a.session = :session and a.type != 6')
                ->setParameter('session', $session->get('Session'))
        ;


        return $qb
                        ->getQuery()
                        ->getSingleResult()
        ;
    }

    public function CalculNbre() {
        $session = new Session();
        $qb = $this->createQueryBuilder('a');

        $qb->select('count(a.valeur)')->where('a.operateur = :op and a.session = :session and a.type != 6')
                ->setParameter('op', $session->get('Codecaisse'))
                ->setParameter('session', $session->get('Session'));

        return $qb
                        ->getQuery()
                        ->getSingleResult()
        ;
    }

    public function detailsTitre() {
        $session = new Session();

        $qb = $this->createQueryBuilder('a');

        $qb->select('sum (a.valeur) as p', 'a.cleControle', 'a.valeur', 'count(a.valeur) as c', 'a.id', 'a.session')->where('a.session = :session')
                ->setParameter('session', $session->get('Session'))
                ->groupBy('a.cleControle');

        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function deployementitre($type) {
        $session = new Session();
        $qb = $this->createQueryBuilder('a');

        $qb->select('a.cleControle', 'a.valeur', 'count(a.valeur) as c', 'a.id')
                ->where('a.cleControle = :type and a.session = :session')
                ->setParameter('session', $session->get('Session'))
                ->setParameter('type', $type)
                ->groupBy('a.valeur');

        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function OperationCaisse() {
        $qb = $this->createQueryBuilder('a');
        $session = new Session();
        $qb->select('a.operateur', 'count(a.valeur) as c', 'sum(a.valeur) as s')
                ->where(' a.session = :session')
                ->setParameter('session', $session->get('Session'))
                ->groupBy('a.operateur');

        return $qb
                        ->getQuery()
                        ->getResult()
        ;
    }

    /*     * ******TICKET KADEOS******** */

    public function sumkadeos() {
        $session = new Session();
        $qb = $this->createQueryBuilder('a');

        $qb->select('sum(a.valeur) ')->where('a.operateur = :op and a.session = :session and a.type = 6')
                ->setParameter('op', $session->get('Codecaisse'))
                ->setParameter('session', $session->get('Session'));

        return $qb
                        ->getQuery()
                        ->getSingleResult()
        ;
    }

    public function countkadeos() {
        $session = new Session();
        $qb = $this->createQueryBuilder('a');

        $qb->select('count(a.valeur) ')->where('a.operateur = :op and a.session = :session and a.type = 6')
                ->setParameter('op', $session->get('Codecaisse'))
                ->setParameter('session', $session->get('Session'));

        return $qb
                        ->getQuery()
                        ->getSingleResult()
        ;
    }

}
